services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - prowlarr
      - sonarr
      - radarr
      - heimdall
      - jellyfin
      - qbittorrent
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/heimdall:/config
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Kiev
    ports:
      - 5055:5055
    volumes:
      - ./conf/jellyseerr:/app/config
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - WEBUI_PORT=8080
    volumes:
      - ./conf/qbit/:/config
      - /mnt/media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./conf/prowlarr:/config
    restart: unless-stopped
    ports:
      - "9696:9696"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./conf/sonarr:/config
      - /mnt/media/tv:/tv #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - "8989:8989"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./conf/radarr:/config
      - /mnt/media/movies:/movies #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - "7878:7878"
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./conf/jellyfin:/config
      - /mnt/media/tv:/data/tvshows
      - /mnt/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *"
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Kiev
    volumes:
      - ./conf/homeassistant:/config
    ports:
      - "8123:8123"
    restart: unless-stopped
version: "3.7"