services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./conf/qbit/:/config
      - /data/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/prowlarr:/config
    restart: unless-stopped
    ports:
      - "9696:9696"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/sonarr:/config
      - /data/tv:/tv #optional
      - /data/downlads:/downloads #optional
    ports:
      - "8989:8989"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/radarr:/config
      - /data/movies:/movies #optional
      - /data/donwloads:/downloads #optional
    ports:
      - "7878:7878"
    restart: unless-stopped
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./conf/homer:/www/assets
    user: 0:0
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d

version: "3.7"
