services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./conf/qbit/:/config
      - /data/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/prowlarr:/config
    restart: unless-stopped
    ports:
      - "9696:9696"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/sonarr:/config
      - /data/tv:/tv #optional
      - /data/downloads:/downloads #optional
    ports:
      - "8989:8989"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/radarr:/config
      - /data/movies:/movies #optional
      - /data/downloads:/downloads #optional
    ports:
      - "7878:7878"
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./conf/jellyfin:/config
      - /data/tv:/data/tvshows
      - /data/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./conf/homer:/www/assets
    user: 0:0
  kuma:
    image: louislam/uptime-kuma
    container_name: kuma
    volumes:
      - ./conf/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - prowlarr
      - sonarr
      - radarr
      - homer
      - jellyfin
      - kuma
      - qbittorrent
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d

version: "3.7"
